version: "3.9"

services:
  qt-dev:
    build: .
    container_name: qt_dev_container
    environment:
      - DISPLAY=host.docker.internal:0.0
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: "host"
    stdin_open: true
    tty: true
